### ISSUE TITLE
Telegram Bot crashes the Server.

### ISSUE THREAD

**Issue by volume4k** [frk1/steamhourboostv2#33]
Hello,
I am trying to boot my CS:GO hours and so far I'm succesful with it. 
But I have one issue that really annoys me. 
When I type the name of any account which is beeing boosted or just anything else than /list the bot will crash the hour booster. I'm running the booster on Debian Strech and my error logs are:
```
internal/crypto/hash.js:84
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'key',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type string, TypedArray, or DataView
    at new Hmac (internal/crypto/hash.js:84:11)
    at Object.createHmac (crypto.js:122:10)
    at Object.exports.generateAuthCode.exports.getAuthCode (/root/steamhourboostv2/node_modules/steam-totp/index.js:43:20)
    at exports.getTimeOffset (/root/steamhourboostv2/node_modules/steam-totp/index.js:28:23)
    at IncomingMessage.res.on (/root/steamhourboostv2/node_modules/steam-totp/index.js:128:4)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! steamhourboostv2@4.1.2 app: `node lib/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steamhourboostv2@4.1.2 app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The detailed logs are: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.n/bin/node', '/root/.n/bin/npm', 'run', 'app' ]
2 info using npm@5.8.0
3 info using node@v9.11.1
4 verbose run-script [ 'preapp', 'app', 'postapp' ]
5 info lifecycle steamhourboostv2@4.1.2~preapp: steamhourboostv2@4.1.2
6 info lifecycle steamhourboostv2@4.1.2~app: steamhourboostv2@4.1.2
7 verbose lifecycle steamhourboostv2@4.1.2~app: unsafe-perm in lifecycle true
8 verbose lifecycle steamhourboostv2@4.1.2~app: PATH: /root/.n/lib/node_modules$
9 verbose lifecycle steamhourboostv2@4.1.2~app: CWD: /root/steamhourboostv2
10 silly lifecycle steamhourboostv2@4.1.2~app: Args: [ '-c', 'node lib/app.js' ]
11 silly lifecycle steamhourboostv2@4.1.2~app: Returned: code: 1  signal: null
12 info lifecycle steamhourboostv2@4.1.2~app: Failed to exec app script
13 verbose stack Error: steamhourboostv2@4.1.2 app: `node lib/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.n/lib/node_modules/npm$
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.n/lib/node_modules/npm$
13 verbose stack     at ChildProcess.emit (events.js:180:13)
14 verbose pkgid steamhourboostv2@4.1.2
15 verbose cwd /root/steamhourboostv2
16 verbose Linux 2.6.32-042stab127.2
17 verbose argv "/root/.n/bin/node" "/root/.n/bin/npm" "run" "app"
18 verbose node v9.11.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error steamhourboostv2@4.1.2 app: `node lib/app.js`
22 error Exit status 1
23 error Failed at the steamhourboostv2@4.1.2 app script.
23 error This is probably not a problem with npm. There is likely additional lo$
24 verbose exit [ 1, true ]
```

It would be awesome if you could help me solving this problem. 
Kind regards 
Jonathan ^^

**Comment by toster234** [comment]
Same problem ;v

**Comment by ZenRact** [comment]
1. Stop steamhourboostv2 if it's running:
`pm2 stop app`

2. I advise you to update the npm's packages. This is optional step, but fresh releases is always better. Especially if you've downloaded steamhourboostv2 a long time ago.
`npm update --save/--save-dev -f`
(this method is safe: packages will be updated only to the version indicated by the developer)

3. Open index.js in steam-totp package using nano:
`nano steamhourboostv2/node_modules/steam-totp/index.js`

4. Find line 36:
`secret = bufferizeSecret(secret);`

5. Add the following above this line:
`if (typeof secret === 'undefined'){
	return '';
}`

**Enjoy!**
![screenshot_1](https://user-images.githubusercontent.com/40814870/42255984-3d6c6b48-7f57-11e8-9a23-80e8b8364ec7.jpg)
