### ISSUE TITLE
Full Issues - 

### ISSUE THREAD

**Issue by CliveCockster** [frk1/steamhourboostv2#9]
Here once the full error in the log is when I want to start the app

Console 
```

> steamhourboostv2@4.0.1 user /root/steamhourboostv2
> coffee src/user.coffee

Error: /root/steamhourboostv2/config/database.json: ENOENT: no such file or directory, open '/root/steamhourboostv2/config/database.json'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.readFileSync (/root/steamhourboostv2/node_modules/jsonfile/index.js:61:22)
    at Object.read (/root/steamhourboostv2/src/database.coffee:9:6)
    at Object.<anonymous> (/root/steamhourboostv2/src/user.coffee:9:21)
    at Object.<anonymous> (/root/steamhourboostv2/src/user.coffee:1:1)
    at Module._compile (module.js:641:30)
    at Object.CoffeeScript.run (/root/steamhourboostv2/node_modules/coffeescript/lib/coffeescript/index.js:63:23)
    at compileScript (/root/steamhourboostv2/node_modules/coffeescript/lib/coffeescript/command.js:265:29)
    at compilePath (/root/steamhourboostv2/node_modules/coffeescript/lib/coffeescript/command.js:220:14)
    at Object.exports.run (/root/steamhourboostv2/node_modules/coffeescript/lib/coffeescript/command.js:141:20)
    at Object.<anonymous> (/root/steamhourboostv2/node_modules/coffeescript/bin/coffee:15:45)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! steamhourboostv2@4.0.1 user: `coffee src/user.coffee`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steamhourboostv2@4.0.1 user script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-11T11_54_45_798Z-debug.log

```

Logfile
```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.n/bin/node', '/root/.n/bin/npm', 'run', 'user' ]
2 info using npm@5.5.1
3 info using node@v9.1.0
4 verbose run-script [ 'preuser', 'user', 'postuser' ]
5 info lifecycle steamhourboostv2@4.0.1~preuser: steamhourboostv2@4.0.1
6 info lifecycle steamhourboostv2@4.0.1~user: steamhourboostv2@4.0.1
7 verbose lifecycle steamhourboostv2@4.0.1~user: unsafe-perm in lifecycle true
8 verbose lifecycle steamhourboostv2@4.0.1~user: PATH: /root/.n/lib/node_modules/npm/bin/node-gyp-bin:/root/steamhourboostv2/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.n/bin
9 verbose lifecycle steamhourboostv2@4.0.1~user: CWD: /root/steamhourboostv2
10 silly lifecycle steamhourboostv2@4.0.1~user: Args: [ '-c', 'coffee src/user.coffee' ]
11 silly lifecycle steamhourboostv2@4.0.1~user: Returned: code: 1  signal: null
12 info lifecycle steamhourboostv2@4.0.1~user: Failed to exec user script
13 verbose stack Error: steamhourboostv2@4.0.1 user: `coffee src/user.coffee`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.n/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at EventEmitter.emit (events.js:224:7)
13 verbose stack     at ChildProcess.<anonymous> (/root/.n/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at ChildProcess.emit (events.js:224:7)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid steamhourboostv2@4.0.1
15 verbose cwd /root/steamhourboostv2
16 verbose Linux 3.16.0-4-amd64
17 verbose argv "/root/.n/bin/node" "/root/.n/bin/npm" "run" "user"
18 verbose node v9.1.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error steamhourboostv2@4.0.1 user: `coffee src/user.coffee`
22 error Exit status 1
23 error Failed at the steamhourboostv2@4.0.1 user script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by frk1** [comment]
Should be fixed with 4.1.0.

Otherwise you can just run `npm run app` once and it will create the missing database.json file.
